travis:
  secure:
    BINSTAR_TOKEN: nKZxjxTzzk/iCBaX7poqLiAnOOiHpE6fuv+HtGPSHXxpPcAt5z9GcAP9p+OQoD6/Z/q+fPQTxKid3tXgVTVTIVGIKfjLTMlHKa4YTBOcqM7dtou6kfr7Rgar348RGW50t3nxSjNQdkxKdDl1t2wDFuJi6bmtf+mGAjKFqcEL15JdkarUorKRHA4ClAepJ1uDApILJYw8KAD7Is33n7z8t+vzEbbXhCQDqNVr53OfQAZdBTA5hJgXr6MxwwyHaZzWPNeyeT89SEnmOxenV4PZoeqDCpS2mqzmTVH6b7eY8N2guRV6C5w6K8wZeqbuDRNlfTWkz8PVYiRaYnei4K0ZBQx1HPLZ3lpT230QfDsaMtTxb4KEOGycYHrwQFcgFfmAegWcucukYHh1IkKsC2KW16Rjl5WNwMsm1oRtF94XjkU0lCynphGWQnY8plVLTlSfRAsct6YN5RHn8RT4GY3KAXFpJbkcZesNSvYEjWn49YoR4OA7q4C8mkQIlakhxJiP5AkZonNky5VzEWiGJ/wK1yXAclJFvBMbegWEeg6d+hVrTEC3EGuurzFaXTW4vsrLE2h8W8VZLQsOd8gb3O/OJqz46stEz2Iy5UAjLdQjr8BqkuaarfOsjewinlEVGC1LzTjksHXJWow4ZxAq8MlkY8I8TyLBSZ+hNnauFljZ1xQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
